services:
  - type: web
    name: lifestyle-design-backend-v2-clean
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    healthCheckPath: /health
    buildTimeoutSec: 1800
    rootDir: .
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    scaling:
      minInstances: 0
      maxInstances: 1
    autoDeploy: true
    branch: main
    regions:
      - virginia