name: Deploy to Render on push

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deploy Hook
        env:
          DEPLOY_HOOK_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          if [ -z "$DEPLOY_HOOK_URL" ]; then
            echo "Missing secret RENDER_DEPLOY_HOOK_URL"; exit 1;
          fi
          curl -sS -X POST "$DEPLOY_HOOK_URL"

